"""Deterministic cleaning rules, one module per object they fix.

`cleaner` is the coordinator: it holds the order of the passes and the public
entry points. The rules here are grouped by what they repair, not by the
engine that produced the defect. `options` carries the context of the passes;
`segments` holds the predicates that several rule modules share.
"""

from raw2md.cleaning.findings import (
    Finding,
    block_shows_defect,
    drop_image_links,
    fix_images_and_report,
    trim_repetition_loops,
)
from raw2md.cleaning.headings import (
    apply_outline_levels,
    close_section_level_gaps,
    collapse_unused_heading_levels,
    detect_oversize_headings,
    detect_run_in_headings,
    drop_running_header_headings,
    group_settled_headings,
    headings_settled_before_nesting,
    join_letter_spaced_headings,
    normalize_heading_numbering,
    normalize_repeated_heading_levels,
    normalize_unnumbered_heading_levels,
    printed_outline,
    split_run_in_headings,
    strip_heading_emphasis,
    strip_heading_leading_glyphs,
    strip_oversize_heading_markers,
)
from raw2md.cleaning.lists import (
    drop_stray_bullet_glyph,
    normalize_lists,
    promote_dingbat_bullet,
    separate_bold_list_marker,
)
from raw2md.cleaning.math import (
    clear_display_span_tail,
    close_unpaired_delimiters,
    defuse_false_math,
    drop_content_free_math_spans,
    drop_orphan_sizers,
    fix_table_math,
    lift_prose_from_display_math,
    normalize_math,
    promote_paragraph_formula,
    reclose_runaway_display_spans,
    reclose_runaway_inline_spans,
    reunite_split_formulas,
    separate_glued_inline_spans,
    strip_math_span_html,
    tag_equation_numbers,
    unwrap_single_glyph_math,
)
from raw2md.cleaning.ocr import (
    DEFAULT_WITNESS_MIN,
    repair_attested_tokens,
    strip_ocr_fabrications,
)
from raw2md.cleaning.options import CleanOptions
from raw2md.cleaning.prose import (
    classify_and_fix,
    collapse_blanks,
    drop_page_furniture,
    drop_paragraph_emphasis,
    join_flattened_paragraphs,
    join_letter_spaced_runs,
    rejoin_hyphenation,
    settle_compound_hyphens,
    strip_alt_file_paths,
    strip_html_anchors,
    strip_line_noise,
)
from raw2md.cleaning.tables import (
    decompose_contents_table,
    drop_bodyless_table,
    drop_empty_table_columns,
    fold_repeated_column_cycle,
    join_contents_entry_breaks,
    join_wrapped_contents_entries,
    keep_table_delimiter_under_header,
    lay_out_table_blocks,
    mend_pipe_block_missing_delimiter,
    open_math_html_cells,
    recut_periodic_stack,
    recut_swallowed_cells,
    reunite_split_tables,
    split_glued_table_header,
    spread_crushed_runs,
)

__all__ = [
    "DEFAULT_WITNESS_MIN",
    "CleanOptions",
    "Finding",
    "apply_outline_levels",
    "block_shows_defect",
    "classify_and_fix",
    "clear_display_span_tail",
    "close_section_level_gaps",
    "close_unpaired_delimiters",
    "collapse_blanks",
    "collapse_unused_heading_levels",
    "decompose_contents_table",
    "defuse_false_math",
    "detect_oversize_headings",
    "detect_run_in_headings",
    "drop_bodyless_table",
    "drop_content_free_math_spans",
    "drop_empty_table_columns",
    "drop_image_links",
    "drop_orphan_sizers",
    "drop_page_furniture",
    "drop_paragraph_emphasis",
    "drop_running_header_headings",
    "drop_stray_bullet_glyph",
    "fix_images_and_report",
    "fix_table_math",
    "fold_repeated_column_cycle",
    "group_settled_headings",
    "headings_settled_before_nesting",
    "join_contents_entry_breaks",
    "join_flattened_paragraphs",
    "join_letter_spaced_headings",
    "join_letter_spaced_runs",
    "join_wrapped_contents_entries",
    "keep_table_delimiter_under_header",
    "lay_out_table_blocks",
    "lift_prose_from_display_math",
    "mend_pipe_block_missing_delimiter",
    "normalize_heading_numbering",
    "normalize_lists",
    "normalize_math",
    "normalize_repeated_heading_levels",
    "normalize_unnumbered_heading_levels",
    "open_math_html_cells",
    "printed_outline",
    "promote_dingbat_bullet",
    "promote_paragraph_formula",
    "reclose_runaway_display_spans",
    "reclose_runaway_inline_spans",
    "recut_periodic_stack",
    "recut_swallowed_cells",
    "rejoin_hyphenation",
    "repair_attested_tokens",
    "reunite_split_formulas",
    "reunite_split_tables",
    "separate_bold_list_marker",
    "separate_glued_inline_spans",
    "settle_compound_hyphens",
    "split_glued_table_header",
    "split_run_in_headings",
    "spread_crushed_runs",
    "strip_alt_file_paths",
    "strip_heading_emphasis",
    "strip_heading_leading_glyphs",
    "strip_html_anchors",
    "strip_line_noise",
    "strip_math_span_html",
    "strip_ocr_fabrications",
    "strip_oversize_heading_markers",
    "tag_equation_numbers",
    "trim_repetition_loops",
    "unwrap_single_glyph_math",
]
